### ISSUE TITLE
Wrong Assumption.

### ISSUE THREAD

**Issue by lemanschik** [felipeplets/esm-examples#6]
Typescript is not designed to emit ESM Code at all
it is at maximum designed to Emit ESCode 

It has not a real Concept of the Module Standard it has a own one. the Typescript Module Standard. 

The whole module part is so out of scope for typescript while they try to solve that. 

When you do Modules with typescript your forced by outer boundary s to use the CommonJS format at present
till all blockers are removed. For example type only modules are on the road.

**Comment by felipeplets** [comment]
> Typescript is not designed to emit ESM Code at all
> it is at maximum designed to Emit ESCode

What do you mean by that? Do you have references to support it?

If you run `npx tsc` in this project and check the ./dist folder you will see ES Modules compatible JavaScript as a result. As far as I know there is no such thing like "ESM Code" and "ESCode"

> It has not a real Concept of the Module Standard it has a own one. the Typescript Module Standard.
>
> The whole module part is so out of scope for typescript while they try to solve that.
>
> When you do Modules with typescript your forced by outer boundary s to use the CommonJS format at present
till all blockers are removed. For example type only modules are on the road.

Do you have any reference? 
What do you mean by type only modules are on the road?

Your issues seems a bit confusing and without a proper goal. What is your goal? Come to the repo tell me I am wrong or help to make it better? If it is to make it better, please let me know why and post any further reference to your affirmations.

Reference for my knowledge: 
- https://www.typescriptlang.org/docs/handbook/2/modules.html
- I've been using JavaScript since 2000 and TypeScript since 2016

**Comment by lemanschik** [comment]
Ok Great as your oldschool you will maybe understand the following claims 
- TypeScript is not Context aware so it does not scope correct.
  - sure it can when you write it directly correct but thats you not typescript doing it
- ESCode references the TypeScript Type Script in typescript there are 2 itms Modules and Scripts

so EScript === ESCode i only call it that way to get a 3 Letter reference as es references also js including 

used without use strict on top which again is something that typescript does not handle correct 

the use strict directive can lead to total other results then without it

**Comment by felipeplets** [comment]
I took some time to understand your message. I can't see any actual issue with the current project and its implementation. 

Regarding #8 which was linked to this issue, I will duplicate my answer here for visibility:

> This repo does not have a working example for web projects to run using ESM at this point in time. If that is your requirement feel free to open an issue requesting it.
